AWS:
  S3:
    Bucket: "avatars241024"
    Region: "eu-north-1"

http:
  port: '8080'

db:
  url: 'postgres://postgres:28072004@localhost:5432/tour?sslmode=disable'

auth:
  accessToken: 15m
  refreshToken: 7d