info:
  contact: {}
paths:
  /auth/verification/traveler/{userID}/avatar:
    delete:
      description: Delete the avatar for a specific user by userID.
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: message
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete user avatar
      tags:
      - Avatar
    get:
      description: Get the avatar URL for a specific user by userID.
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: url
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get user avatar
      tags:
      - Avatar
    post:
      consumes:
      - multipart/form-data
      description: Upload a new avatar for a user by userID.
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: integer
      - description: Avatar file
        in: formData
        name: avatar
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: url
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Upload user avatar
      tags:
      - Avatar
swagger: "2.0"
